driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver:
      image: dokken/centos-7
  - name: fedora-25
    driver:
      image: dokken/fedora-25

suites:
  - name: default
    run_list: test::default
